import {
  type InterpretationResult,
  type QuestionnaireDefinition,
  type Threshold,
} from "@/features/assessment/engine/types";

const pdq4FullThresholds: readonly Threshold[] = [
  {
    min: 0,
    max: 99,
    label: "Score global PDQ-4+",
    severity: "moderate",
    clinicalMeaning:
      "Nombre total de reponses Vrai sur 99 items. Outil de dépistage uniquement; un entretien clinique structure est necessaire pour le diagnostic.",
  },
];

function interpret(totalScore: number): InterpretationResult {
  const match = pdq4FullThresholds.find(
    (threshold) => totalScore >= threshold.min && totalScore <= threshold.max
  );

  if (!match) {
    throw new Error(`Score PDQ-4+ complet hors plage: ${totalScore}`);
  }

  return {
    label: match.label,
    severity: match.severity,
    clinicalMeaning: match.clinicalMeaning,
  };
}

export const pdq4FullDefinition: QuestionnaireDefinition = {
  id: "pdq4Full",
  version: "1.0.0",
  title: "PDQ-4+ complet (99 items)",
  items: [    { id: "pdq4full_1", prompt: "J’évite de travailler avec des gens qui pourraient me critiquer." },
    { id: "pdq4full_2", prompt: "Je ne peux prendre aucune décision sans le conseil ou le soutien des autres." },
    { id: "pdq4full_3", prompt: "Je me perds souvent dans les détails et n’ai plus de vision d’ensemble." },
    { id: "pdq4full_4", prompt: "J’ai besoin d’être au centre de l’attention générale." },
    { id: "pdq4full_5", prompt: "J’ai accompli beaucoup plus de choses que ce que les autres me reconnaissent." },
    { id: "pdq4full_6", prompt: "Je ferais n’importe quoi pour éviter que ceux qui me sont chers ne me quittent." },
    { id: "pdq4full_7", prompt: "Les autres se sont plaints que je ne sois pas à jour dans mon travail ou que je ne tienne pas mes engagements." },
    { id: "pdq4full_8", prompt: "J’ai eu des problèmes avec la loi à plusieurs reprises (ou j’en aurais eu si j’avais été pris(e))." },
    { id: "pdq4full_9", prompt: "Passer du temps avec ma famille ou avec des amis ne m’intéresse pas vraiment." },
    { id: "pdq4full_10", prompt: "Je reçois des messages particuliers de ce qui se passe autour de moi." },
    { id: "pdq4full_11", prompt: "Je sais que, si je les laisse faire, les gens vont profiter de moi ou chercher à me tromper." },
    { id: "pdq4full_12", prompt: "Parfois, je me sens bouleversé(e)." },
    { id: "pdq4full_13", prompt: "Je ne me lie avec les gens que lorsque je suis sûr(e) qu’ils m’aiment." },
    { id: "pdq4full_14", prompt: "Je suis habituellement déprimé(e)." },
    { id: "pdq4full_15", prompt: "Je préfère que ce soit les autres qui soient responsables pour moi." },
    { id: "pdq4full_16", prompt: "Je perds du temps à m’efforcer de tout faire parfaitement." },
    { id: "pdq4full_17", prompt: "Je suis plus « sexy » que la plupart des gens." },
    { id: "pdq4full_18", prompt: "Je me surprends souvent à penser à la personne importante que je suis ou que je vais devenir un jour." },
    { id: "pdq4full_19", prompt: "J’aime ou je déteste quelqu’un, il n’y a pas de milieu pour moi." },
    { id: "pdq4full_20", prompt: "Je me bagarre beaucoup physiquement." },
    { id: "pdq4full_21", prompt: "Je sens tres bien que les autres ne me comprennent pas ou ne m'apprecient pas." },
    { id: "pdq4full_22", prompt: "J’aime mieux faire les choses tout(e) seul(e) qu’avec les autres." },
    { id: "pdq4full_23", prompt: "Je suis capable de savoir que certaines choses vont se produire avant qu’elles n’arrivent." },
    { id: "pdq4full_24", prompt: "Je me demande souvent si les gens que je connais sont dignes de confiance." },
    { id: "pdq4full_25", prompt: "Parfois, je parle des gens dans leur dos." },
    { id: "pdq4full_26", prompt: "Je suis inhibé(e) dans mes relations intimes parce que j’ai peur d’être ridiculisé(e)." },
    { id: "pdq4full_27", prompt: "Je crains de perdre le soutien des autres si je ne suis pas d’accord avec eux." },
    { id: "pdq4full_28", prompt: "Je souffre d’un manque d’estime de moi." },
    { id: "pdq4full_29", prompt: "Je place mon travail avant la famille, les amis ou les loisirs." },
    { id: "pdq4full_30", prompt: "Je montre facilement mes émotions." },
    { id: "pdq4full_31", prompt: "Seules certaines personnes tout à fait spéciales sont capables de m’apprécier et de me comprendre." },
    { id: "pdq4full_32", prompt: "Je me demande souvent qui je suis réellement." },
    { id: "pdq4full_33", prompt: "J’ai de la peine à payer mes factures parce que je ne reste jamais bien longtemps dans le même emploi." },
    { id: "pdq4full_34", prompt: "Le sexe ne m’intéresse tout simplement pas." },
    { id: "pdq4full_35", prompt: "Les autres me trouvent « soupe au lait » (susceptible) et colérique." },
    { id: "pdq4full_36", prompt: "Il m’arrive souvent de percevoir ou de ressentir des choses alors que les autres ne perçoivent rien." },
    { id: "pdq4full_37", prompt: "Les autres vont utiliser ce que je dis contre moi." },
    { id: "pdq4full_38", prompt: "Il y a des gens que je n’aime pas." },
    { id: "pdq4full_39", prompt: "Je suis plus sensible à la critique et au rejet que la plupart des gens." },
    { id: "pdq4full_40", prompt: "J’ai de la peine à commencer quelque chose si je dois le faire tout(e) seul(e)." },
    { id: "pdq4full_41", prompt: "J’ai un sens moral plus élevé que les autres gens." },
    { id: "pdq4full_42", prompt: "Je suis mon « propre » pire critique." },
    { id: "pdq4full_43", prompt: "Je me sers de mon apparence pour attirer l’attention dont j’ai besoin." },
    { id: "pdq4full_44", prompt: "J’ai un immense besoin que les autres gens me remarquent et me fassent des compliments." },
    { id: "pdq4full_45", prompt: "J’ai essayé de me blesser ou de me tuer." },
    { id: "pdq4full_46", prompt: "Je fais beaucoup de choses sans penser aux conséquences." },
    { id: "pdq4full_47", prompt: "Il n’y a pas beaucoup d’activités qui retiennent mon intérêt." },
    { id: "pdq4full_48", prompt: "Les gens ont souvent de la difficulté à comprendre ce que je dis." },
    { id: "pdq4full_49", prompt: "Je m’oppose verbalement à mes supérieurs lorsqu’ils me disent de quelle façon faire mon travail." },
    { id: "pdq4full_50", prompt: "Je suis très attentif(ve) à déterminer la signification réelle de ce que les gens disent." },
    { id: "pdq4full_51", prompt: "Je n’ai jamais dit un mensonge." },
    { id: "pdq4full_52", prompt: "J’ai peur de rencontrer de nouvelles personnes parce que je me sens inadéquat(e)." },
    { id: "pdq4full_53", prompt: "J’ai tellement envie que les gens m’aiment que j’en viens à me porter volontaire pour des choses qu’en fait je préfèrerais ne pas faire." },
    { id: "pdq4full_54", prompt: "J’ai accumulé énormément de choses dont je n’ai pas besoin, mais que je suis incapable de jeter." },
    { id: "pdq4full_55", prompt: "Bien que je parle beaucoup, les gens me disent que j’ai de la peine à faire passer mes idées." },
    { id: "pdq4full_56", prompt: "Je me fais beaucoup de soucis." },
    { id: "pdq4full_57", prompt: "J’attends des autres qu’ils m’accordent des faveurs, quand bien même il n’est pas dans mes habitudes de leur en consentir." },
    { id: "pdq4full_58", prompt: "Je suis une personne dont l’humeur est très changeante." },
    { id: "pdq4full_59", prompt: "Mentir m’est facile et je le fais souvent." },
    { id: "pdq4full_60", prompt: "Je ne suis pas intéressé(e) à avoir des amis proches." },
    { id: "pdq4full_61", prompt: "Je suis souvent sur mes gardes, de peur que l’on ne profite de moi." },
    { id: "pdq4full_62", prompt: "Je n’oublie pas et je ne pardonne jamais à ceux qui m’ont fait du mal." },
    { id: "pdq4full_63", prompt: "J’en veux à ceux qui ont plus de chance que moi." },
    { id: "pdq4full_64", prompt: "Une guerre atomique ne serait peut-être pas une si mauvaise idée." },
    { id: "pdq4full_65", prompt: "Lorsque je suis seul(e), je me sens désemparé(e) et incapable de m’occuper de moi-même." },
    { id: "pdq4full_66", prompt: "Si les autres sont incapables de faire les choses correctement, je préfère les faire moi-même." },
    { id: "pdq4full_67", prompt: "J’ai un penchant pour le « dramatique »." },
    { id: "pdq4full_68", prompt: "Il y a des gens qui pensent que je profite des autres." },
    { id: "pdq4full_69", prompt: "Il me semble que ma vie est sans intérêt et n’a aucun sens." },
    { id: "pdq4full_70", prompt: "Je suis critique à l’égard des autres." },
    { id: "pdq4full_71", prompt: "Je ne me soucie pas de ce que les autres peuvent avoir à dire à mon sujet." },
    { id: "pdq4full_72", prompt: "J’ai des difficultés à soutenir un face-à-face." },
    { id: "pdq4full_73", prompt: "Les autres se sont souvent plaints que je ne remarquais pas qu’ils étaient bouleversés." },
    { id: "pdq4full_74", prompt: "En me regardant, les autres pourraient penser que je suis plutôt original(e), excentrique et bizarre." },
    { id: "pdq4full_75", prompt: "J’aime faire des choses risquées." },
    { id: "pdq4full_76", prompt: "J’ai beaucoup menti dans ce questionnaire." },
    { id: "pdq4full_77", prompt: "Je me plains beaucoup de toutes les difficultés que j’ai." },
    { id: "pdq4full_78", prompt: "J’ai de la peine à contrôler ma colère ou mes sautes d’humeur." },
    { id: "pdq4full_79", prompt: "Certaines personnes sont jalouses de moi." },
    { id: "pdq4full_80", prompt: "Je suis facilement influencé(e) par les autres." },
    { id: "pdq4full_81", prompt: "J’estime être économe, mais les autres me trouvent pingre." },
    { id: "pdq4full_82", prompt: "Quand une relation proche prend fin, j’ai besoin de m’engager immédiatement dans une autre relation." },
    { id: "pdq4full_83", prompt: "Je souffre d’un manque d’estime de soi." },
    { id: "pdq4full_84", prompt: "Je suis un(e) pessimiste." },
    { id: "pdq4full_85", prompt: "Je ne perds pas mon temps à répliquer aux gens qui m’insultent." },
    { id: "pdq4full_86", prompt: "Etre au milieu des gens me rend nerveux(se)." },
    { id: "pdq4full_87", prompt: "Dans les situations nouvelles, je crains d’être mal à l’aise." },
    { id: "pdq4full_88", prompt: "Je suis terrifié(e) à l’idée de devoir m’assumer tout(e) seul(e)." },
    { id: "pdq4full_89", prompt: "Les gens se plaignent que je sois aussi têtu(e) qu’une mule." },
    { id: "pdq4full_90", prompt: "Je prends les relations avec les autres beaucoup plus au sérieux qu’ils ne le font eux-mêmes." },
    { id: "pdq4full_91", prompt: "Je peux être méchant(e) avec quelqu’un à un moment et, dans la minute qui suit lui présenter mes excuses." },
    { id: "pdq4full_92", prompt: "Les autres pensent que je suis prétentieux(se)." },
    { id: "pdq4full_93", prompt: "Quand je suis stressé(e), il m’arrive de devenir « parano » ou même de perdre conscience." },
    { id: "pdq4full_94", prompt: "Tant que j’obtiens ce que je veux, il m’est égal que les autres en souffrent." },
    { id: "pdq4full_95", prompt: "Je garde mes distances à l’égard des autres." },
    { id: "pdq4full_96", prompt: "Je me demande souvent si ma femme (mari, ami(e)) m’a trompé(e)." },
    { id: "pdq4full_97", prompt: "Je me sens souvent coupable." },
    { id: "pdq4full_98", prompt: "J’ai fait, de manière impulsive, des choses (comme celles indiquées ci-dessous) qui pourraient me créer des problèmes. a. Dépenser plus d’argent que je n’en ai. b.Avoir des rapports sexuels avec des gens que je connais à peine. c.Boire trop. d.Prendre des drogues. e.Manger de façon boulimique. f. Conduire imprudemment." },
    { id: "pdq4full_99", prompt: "Lorsque j’étais enfant (avant l’âge de 15 ans), j’étais une sorte de délinquant(e) juvénile et je faisais certaines des choses ci-dessous. a. J’étais considéré(e) comme une brute. b. J’ai souvent déclenché des bagarres avec les autres enfants. c. J’ai utilisé une arme dans mes bagarres. d. J’ai volé ou agressé des gens. e. J’ai été physiquement cruel(le) avec d’autres gens. f. J’ai été physiquement cruel(le) avec des animaux. g. J’ai forcé quelqu’un à avoir des rapports sexuels avec moi. h. J’ai beaucoup menti. i. J’ai découché sans la permission de mes parents. j. J’ai dérobé des choses aux autres. k. J’ai allumé des incendies. l. J’ai cassé des fenêtres ou détruit la propriété d’autrui. m.Je me suis plus d’une fois enfui(e) de la maison en pleine nuit. n. J’ai commencé à beaucoup manquer l’école avant l'âge de 13 ans. o. Je me suis introduit(e) par effraction dans la maison, le bâtiment ou la voiture de quelqu’un." },
  ],
  scale: {
    min: 0,
    max: 1,
    anchors: {
      0: "Faux",
      1: "Vrai",
    },
  },
  scoringRules: {
    method: "sum",
    requiredItems: 99,
    source:
      "PDQ-4+ (Hyler). Version complete 99 items Vrai/Faux; score global de dépistage. Les seuils diagnostiques specifiques par trouble requierent la grille complete et validation clinique.",
  },
  thresholds: pdq4FullThresholds,
  interpretation: interpret,
};
